### ISSUE TITLE
Cannot build with GCC 4.9

### ISSUE THREAD

**Issue by birkenfeld** [scgmlz/BornAgain#875]
https://www.bornagainproject.org/documentation/getting-started/installation/linux-detailed/third-party/ states that GCC >= 4.9 is required, but it leads to the following errors:

```
[   99s] /home/abuild/rpmbuild/BUILD/BornAgain-1.16.0/Core/InputOutput/DataFormatUtils.cpp: In function 'std::unique_ptr<IAxis> DataFormatUtils::createAxis(std::istream&)':
[   99s] /home/abuild/rpmbuild/BUILD/BornAgain-1.16.0/Core/InputOutput/DataFormatUtils.cpp:93:56: error: use of deleted function 'std::basic_istringstream<char>::basic_istringstream(const std::basic_istringstream<char>&)'
[   99s]      auto iss = getAxisStringRepresentation(input_stream);
[   99s]                                                         ^
```

GCC 4.9 is what we're currently packaging for CentOS 6, so if compatibility could easily be restored it would save us a potentially painful compiler upgrade until we switch to CentOS 8.

CC @cfelder

**Comment by gpospelov** [comment]
Thank you for reporting this. BornAgain requires full C++14 support in the compiler, which for gcc will be version 5.0. I'm sorry for misleading statement on a web page, I will change it. Please also note, that by the end of this year we will rise our minimal compiler requirement to full C++17 support. I understand, that system compiler upgrade is painful, but can we just have additional compilers in /usr/local, like gcc6, gcc8, similarly to what JCNS does centrally?

**Comment by birkenfeld** [comment]
Yes, we have the mentioned GCC 4.9 in /usr/local and we're using it to build all packages that need C++11/14 support. It's just that updating it is quite a bit of work since we need to rebuild all those packages and make sure they still work with the newer compiler version.

The "centrally updated /usr/local" is simply not an option for us, since it means either syncing a huge tree onto every machine that needs local software, even if it's just one package, or relying on a network filesystem, which we can't do at the instruments. Both of these options also have issues with traceability of which software was in use at a machine at a certain point in time, and the inability to update packages independently on different hosts.

**Comment by birkenfeld** [comment]
I've built a GCC 7.4 now, hopefully that lasts until we stop supporting CentOS 6. BornAgain works fine with it.

**Comment by gpospelov** [comment]
Nice, 
thank you very much!
